result = 19
result += 19
print("result += 19 ans: ", result)
result -= 19
print("result -= 19 ans: ", result)
result *= 19
print("result *= 19 ans: ", result)
result //= 19
print("result //= 19 ans: ", result)
result %= 19
print("result %= 19 ans: ", result)